name: Deploy website on push

on:
  push:
    branches:
      - main  # Adjust this to your main branch

jobs:
  deploy:
    name: FTP Deploy
    runs-on: ubuntu-latest

    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v3
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: pliris.wuaze.com
        username: ${{ secrets.FTPUSERNAME }}
        password: ${{ secrets.FTPPASSWORD }}
        protocol: ftp
        server-dir: /htdocs/
