name: Deploy website on push

on:
  push:
    branches:
      - main  # Adjust this to your main branch

jobs:
  deploy:
    name: FTP Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Use the latest version

      - name: Install lftp
        run: sudo apt-get install lftp

      - name: Deploy to FTP server
        env:
          FTP_USERNAME: ${{ secrets.FTPUSERNAME }}
          FTP_PASSWORD: ${{ secrets.FTPPASSWORD }}
        run: |
          lftp -c "
          open -u $FTP_USERNAME,$FTP_PASSWORD ftp://pliris.wuaze.com;
          mirror -R ./ /htdocs/;
          bye
          "
