name: Deploy website on push

on:
  push:
    branches:
      - main  # Adjust this to your main branch

jobs:
  deploy:
    name: FTP Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to FTP server
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: pliris.wuaze.com
          username: ${{ secrets.FTPUSERNAME }}
          password: ${{ secrets.FTPPASSWORD }}
          protocol: ftp  # Use 'ftp' for FTP
          local-dir: .  # Adjust this to your local directory if needed
          server-dir: /htdocs/  # The directory on your server

